version: 0.2

env:

  variables:
    DOCKER_PASSWORD: remoteRepositorieKeys:GitHub_key
    DOCKER_USERNAME: "manrodri"

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ./src
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG